['mobile-fix.css','mobile-polish.css','corporate-polish.css','showcase-polish.css','motion-polish.css'].forEach(href=>{const link=document.createElement('link');link.rel='stylesheet';link.href=href;document.head.append(link)});
document.querySelector('.desktop-mail img').src='assets/amp-dev.png';document.querySelector('.desktop-mail img').alt='AMP email development sample';document.querySelector('.mobile-mail img').src='assets/LP.jpg';document.querySelector('.mobile-mail img').alt='Landing page sample with an illustrated robot';
document.querySelector('.about .overline').textContent='03 / EXPERIENCE';document.querySelector('.contact .overline').textContent='04 / AVAILABLE FOR EMAIL DEVELOPMENT ROLES';
document.querySelector('.work .section-title h2').innerHTML='Work that ships.<br><em>Open the experience.</em>';document.querySelector('.work .section-title>p:last-child').textContent='Responsive campaigns, interactive email and landing-page builds—open any project to explore the live work.';
const menu=document.querySelector('.menu'),nav=document.querySelector('nav');menu.onclick=()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open);menu.innerHTML=open?'CLOSE <span>−</span>':'MENU <span>+</span>'};nav.querySelectorAll('a').forEach(a=>a.onclick=()=>{nav.classList.remove('open');menu.innerHTML='MENU <span>+</span>';menu.setAttribute('aria-expanded','false')});
const projects={amp:{type:'01 / AMP EMAILER',title:'AMP Emailer',image:'assets/amp-dev.png',url:'https://lokeshp26.github.io/Amp/'},interactive:{type:'02 / INTERACTIVE EMAILER',title:'Interactive E-mailer',image:'assets/interactive_email.jpg',url:'https://lokeshp26.github.io/Interactive_Html/'},standard:{type:'03 / STANDARD EMAIL',title:'Standard Email Template',image:'assets/standard_html.jpg',url:'https://lokeshp26.github.io/Standard_HTML/'},newsletter:{type:'04 / NEWSLETTER',title:'Newsletter Template',image:'assets/img_based_v.jpg',url:'https://lokeshp26.github.io/Image_based_Html/'},cms:{type:'05 / CMS BLOCK',title:'CMS Block',image:'assets/cms.jpg',url:'https://lokeshp26.github.io/CMS/'},landing:{type:'06 / LANDING PAGE',title:'Landing Page',image:'assets/LP.jpg',url:'https://lokeshp26.github.io/LP1/'}};
const dialog=document.querySelector('.sample-modal');document.querySelectorAll('.open-project').forEach(card=>card.onclick=()=>{const project=projects[card.dataset.project];document.querySelector('#modal-type').textContent=project.type;document.querySelector('#modal-title').textContent=project.title;const image=document.querySelector('#modal-image');image.src=project.image;image.alt=project.title+' preview';document.querySelector('#modal-link').href=project.url;dialog.showModal()});document.querySelector('.modal-close').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()};document.querySelector('#year').textContent=new Date().getFullYear();
if(!matchMedia('(prefers-reduced-motion: reduce)').matches){const animated=document.querySelectorAll('.work,.expertise,.about,.contact,.sample-card');animated.forEach((item,index)=>{item.classList.add('scroll-reveal');item.style.setProperty('--delay',`${Math.min(index%6,5)*70}ms`)});const reveal=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');reveal.unobserve(entry.target)}}),{threshold:.12});animated.forEach(item=>reveal.observe(item));}
const navLinks=[...document.querySelectorAll('nav a')],navSections=navLinks.map(link=>document.querySelector(link.getAttribute('href'))).filter(Boolean);const navObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){navLinks.forEach(link=>link.classList.toggle('is-current',link.getAttribute('href')===`#${entry.target.id}`))}}),{rootMargin:'-35% 0px -55% 0px'});navSections.forEach(section=>navObserver.observe(section));
if(!matchMedia('(prefers-reduced-motion: reduce)').matches){const hero=document.querySelector('.hero'),art=document.querySelector('.hero-showcase');hero.addEventListener('pointermove',event=>{if(innerWidth>850){const x=(event.clientX/innerWidth-.5)*8,y=(event.clientY/innerHeight-.5)*8;art.style.transform=`translate(${x}px,${y}px)`}});hero.addEventListener('pointerleave',()=>art.style.transform='');const metrics=[['03+',3],['100+',100],['30+',30]];const proof=document.querySelector('.hero-proof');new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;metrics.forEach(([label,max],index)=>{const node=proof.querySelectorAll('strong')[index<2?index:index+1];let value=0;const step=Math.max(1,Math.ceil(max/28));const tick=()=>{value=Math.min(value+step,max);node.textContent=`${String(value).padStart(max<10?2:1,'0')}+`;if(value<max)requestAnimationFrame(tick)};tick()});entry.target.classList.add('metrics-live')}),{threshold:.6}).observe(proof);}
